# Generated by Django 5.2.5 on 2025-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('service_process', models.TextField(verbose_name='服务流程')),
                ('duration', models.IntegerField(verbose_name='基础服务时长(分钟)')),
                ('is_door_to_door', models.BooleanField(default=True, verbose_name='是否上门服务')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='服务要求')),
                ('precautions', models.TextField(blank=True, null=True, verbose_name='注意事项')),
            ],
        ),
    ]
