# Generated by Django 5.2.5 on 2025-08-26 05:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='用户名')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='手机号格式不正确', regex='^\\+?1?\\d{9,15}$')], verbose_name='手机号')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='U', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('openid', models.CharField(blank=True, max_length=128, null=True)),
                ('unionid', models.CharField(blank=True, max_length=128, null=True)),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('is_worked', models.BooleanField(default=False, verbose_name='是否工作')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
