# Generated by Django 5.2.5 on 2025-08-26 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('wechat_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('recharge', 'Recharge')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('alipay', 'Alipay'), ('wechat', 'WeChat'), ('unionpay', 'UnionPay'), ('zhifubao', '支护宝'), ('other', 'Other')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_bills', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='预约日期')),
                ('scheduled_time', models.TimeField(verbose_name='预约时间')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='预计时长（分钟）')),
                ('service_address', models.TextField(verbose_name='服务地址')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基础服务价格')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='附加服务价格')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价格')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('in_progress', '服务中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('customer_notes', models.TextField(blank=True, verbose_name='客户备注')),
                ('staff_notes', models.TextField(blank=True, verbose_name='员工备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_order', to='bill.bill', verbose_name='账单')),
            ],
            options={
                'verbose_name': '服务订单',
                'verbose_name_plural': '服务订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
