# Generated by Django 5.2.5 on 2025-08-26 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('pet', '0001_initial'),
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='pets',
            field=models.ManyToManyField(to='pet.pet', verbose_name='服务宠物'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='staff.staff', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='user.user', verbose_name='用户'),
        ),
    ]
