# Generated by Django 5.2.5 on 2025-11-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_initial'),
        ('service', '0003_alter_additionalservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='service.additionalservice', verbose_name='附加服务'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='base_service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='service.servicemodel', verbose_name='基础服务'),
            preserve_default=False,
        ),
    ]
