# Generated by Django 5.2.5 on 2025-11-06 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_serviceorder_additional_services_and_more'),
        ('pet', '0003_petdiary_cover_image'),
        ('service', '0003_alter_additionalservice_options_and_more'),
        ('staff', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at'], 'verbose_name': '支付订单', 'verbose_name_plural': '支付订单'},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='wechat_transaction_id',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='bill',
            name='failure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='失败原因'),
        ),
        migrations.AddField(
            model_name='bill',
            name='original_bill',
            field=models.ForeignKey(blank=True, help_text='如果是退款订单，关联原支付订单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_bills', to='bill.bill', verbose_name='原支付订单'),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='bill',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='退款金额'),
        ),
        migrations.AddField(
            model_name='bill',
            name='refund_reason',
            field=models.TextField(blank=True, verbose_name='退款原因'),
        ),
        migrations.AddField(
            model_name='bill',
            name='service_order',
            field=models.ForeignKey(blank=True, help_text='关联的服务订单（充值等操作可能没有服务订单）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='bill.serviceorder', verbose_name='服务订单'),
        ),
        migrations.AddField(
            model_name='bill',
            name='third_party_no',
            field=models.CharField(blank=True, help_text='微信/支付宝等第三方支付订单号', max_length=100, null=True, verbose_name='第三方订单号'),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='取消原因'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='优惠金额'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最终支付价格'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='单位：元', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='账单描述'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='out_trade_no',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='商户订单号'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('wechat', '微信支付'), ('alipay', '支付宝'), ('balance', '余额支付'), ('cash', '现金支付'), ('other', '其他')], max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('pending', '待支付'), ('processing', '处理中'), ('success', '支付成功'), ('failed', '支付失败'), ('cancelled', '已取消'), ('refunded', '已退款')], db_index=True, default='pending', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='transaction_type',
            field=models.CharField(choices=[('payment', '订单支付'), ('refund', '订单退款'), ('recharge', '余额充值'), ('withdraw', '余额提现')], db_index=True, max_length=20, verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='user.user', verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='附加服务价格'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础服务价格'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to='staff.staff', verbose_name='服务员工'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('draft', '待支付'), ('paid', '已支付'), ('confirmed', '已确认'), ('assigned', '已分配'), ('in_progress', '服务中'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款')], db_index=True, default='draft', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='总价格'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'payment_status'], name='bill_bill_user_id_79b247_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['service_order', 'payment_status'], name='bill_bill_service_94998e_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['out_trade_no'], name='bill_bill_out_tra_5becec_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['created_at'], name='bill_bill_created_2e4bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['user', 'status'], name='bill_servic_user_id_1da68c_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='bill_servic_schedul_de6122_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceorder',
            index=models.Index(fields=['created_at'], name='bill_servic_created_d81136_idx'),
        ),
    ]
