# Generated by Django 5.2.5 on 2025-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_bill_options_remove_bill_wechat_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='province',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
