"""
Django settings for DjangoPet project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ

from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab

env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#8=f+k6l@_4nf32jaoz+6w(q7x-&f7odcasgt7=jcr!b+fq8dw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 配置小程序
MINI_PROGRAM_SETTINGS = {
    "USER": {
        "APPID": env('WECHAT_APP_ID'),
        "APPSECRET": env('WECHAT_APP_SECRET')
    }
}

# 调试信息模式（True = 不真正发送短信，只打印日志）
SMS_DEBUG_MODE = False

# 阿里云配置
ALIYUN_SMS_SIGN_NAME = env('ALIYUN_SMS_SIGN_NAME')

# 配置阿里云
ALIYUN_ACCESS_KEY_ID = env('ALIYUN_ACCESS_KEY_ID')
ALIYUN_ACCESS_KEY_SECRET = env('ALIYUN_ACCESS_KEY_SECRET')

CSRF_TRUSTED_ORIGINS = ['https://delock.top:8080', 'https://pet.yimengzhiyuan.com:8080','http://localhost:5173']

# redis配置
REDIS_PASSWORD = env('REDIS_PASSWORD')
# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'django_celery_beat',
    'django_celery_results',

    'corsheaders',

    # 已检查
    'attach',
    'bill',
    'community',
    'user',
    'feedback',
    'pet',
    'points',
    'strays',
    'prize',
    # 新增
    'address',
    'attract',
    'campaigns',
    'comments',
    'managers',
    'merchants',
    'pay',
    'product',
    'promotions',
    'services',
    'staffs',
    'wallet',
    'adoption',
    'care',



]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoPet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoPet.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DATABASE_ENGINE'),
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
        'OPTIONS': {
            # 设置数据库连接的时区（根据你的实际时区调整）
            'init_command': "SET time_zone = '+08:00'",
            'charset': 'utf8mb4',
        },
    }
}

NEO4J_URI = env('NEO4J_URI', default='bolt://localhost:7687')
NEO4J_USER = env('NEO4J_USER', default='neo4j')
NEO4J_PASSWORD = env('NEO4J_PASSWORD', default='password')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 配置项目的认证类
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',
                                'rest_framework.filters.OrderingFilter', ],

}

# 配置token信息
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),  # 访问令牌的有效期为 365 天
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),  # 刷新令牌的有效期，可以根据需要调整
    'ROTATE_REFRESH_TOKENS': True,  # 启用刷新令牌旋转
    'BLACKLIST_AFTER_ROTATION': True,  # 旋转后使旧的刷新令牌失效
}

# 配置微信支付
WECHAT_PAY_CONFIG = {
    'MINI_APPID': env('APPID', default=''),  # 小程序APPID
    'APP_PAY_APPID': env('WECHAT_APP_PAY_APPID', default=''),  # APP支付APPID（微信开放平台移动应用）
    'MCH_ID': env('MCH_ID', default=''),
    'API_KEY': env('API_KEY', default=''),  # V2 API密钥
    'CERT_PATH': env('CERT_PATH', default=''),  # 退款和提现需要
    'KEY_PATH': env('KEY_PATH', default=''),  # 退款和提现需要
    'NOTIFY_URL': env('NOTIFY_URL', default=''),  # 支付回调地址基础URL
}

# 配置支付宝支付
ALIPAY_CONFIG = {
    'APPID': env('ALIPAY_APPID', default=''),
    'APP_PRIVATE_KEY': env('ALIPAY_APP_PRIVATE_KEY', default=''),  # 应用私钥
    'ALIPAY_PUBLIC_KEY': env('ALIPAY_PUBLIC_KEY', default=''),  # 支付宝公钥
    'NOTIFY_URL': env('ALIPAY_NOTIFY_URL', default=''),  # 支付宝异步回调地址
    'RETURN_URL': env('ALIPAY_RETURN_URL', default=''),  # 支付宝同步跳转地址（APP支付不需要，可留空）
    'DEBUG': env.bool('ALIPAY_DEBUG', default=False),  # 沙箱环境开关
    'SIGN_TYPE': 'RSA2',  # 签名类型，固定RSA2
}

# 配置缓存为Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env('REDIS_LOCATION'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            'IGNORE_EXCEPTIONS': True,
        }
    }
}

# 配置log日志
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)  #
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'utils.logging_handlers.GzipRotatingFileHandler',  # 替换为实际路径
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,  # 保留 5 个备份
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        '': {  # 根日志记录器
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'myapp': {  # 针对 myapp 的日志记录器
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'celery': {
                'handlers': ['file', 'console'],
                'level': 'INFO',
                'propagate': False,
            },
        'bill': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'sms': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'adoption': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },

    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='django-db')

# 序列化
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# 时区: 跟 Django 保持一致
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# 任务路由 — 按业务拆队列,防互相阻塞
CELERY_TASK_ROUTES = {
    # ── QSever 原有路由(bill/campaigns/promotions 共用) ──
    'bill.tasks.task_try_auto_dispatch': {'queue': 'dispatch'},
    'bill.tasks.task_expire_pending_dispatches': {'queue': 'dispatch'},
    'bill.tasks.task_dispatch_upcoming_deliveries': {'queue': 'dispatch'},
    'bill.tasks.task_activate_due_subscriptions': {'queue': 'default'},
    'bill.tasks.task_send_sms': {'queue': 'sms'},

    # ── 领养模块: 通知走 default,定时扫描走 adoption 队列 ──
    'adoption.tasks.notify_new_application': {'queue': 'default'},
    'adoption.tasks.notify_application_result': {'queue': 'default'},
    'adoption.tasks.notify_application_cancelled': {'queue': 'default'},
    'adoption.tasks.notify_update_submitted': {'queue': 'default'},
    'adoption.tasks.alert_abnormal_update': {'queue': 'default'},
    'adoption.tasks.notify_violation': {'queue': 'default'},
    'adoption.tasks.notify_update_reminder': {'queue': 'default'},
    'adoption.tasks.scan_approve_expired': {'queue': 'adoption'},
    'adoption.tasks.scan_overdue_updates': {'queue': 'adoption'},
    'adoption.tasks.scan_restriction_lift': {'queue': 'adoption'},
}

CELERY_TASK_DEFAULT_QUEUE = 'default'

# 可靠性: worker 处理完才 ack,宕机不丢任务
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 任务超时
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_SOFT_TIME_LIMIT = 50

# Beat 用 DB 调度器,可在 admin 后台改间隔
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

CELERY_BEAT_SCHEDULE = {
    'refresh-dashboard-daily': {
        'task': 'managers.tasks.refresh_dashboard_task',
        'schedule': crontab(hour=3, minute=0),   # 每天 03:00(Asia/Shanghai)
    },
}
