# Generated by Django 5.2.5 on 2025-10-20 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_initial'),
        ('pet', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at'], 'verbose_name': '宠物', 'verbose_name_plural': '宠物'},
        ),
        migrations.AlterModelOptions(
            name='petcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '宠物分类', 'verbose_name_plural': '宠物分类'},
        ),
        migrations.AlterModelOptions(
            name='petdiary',
            options={'ordering': ['-diary_date', '-created_at'], 'verbose_name': '宠物日记', 'verbose_name_plural': '宠物日记'},
        ),
        migrations.AlterModelOptions(
            name='petservicerecord',
            options={'ordering': ['-created_at'], 'verbose_name': '宠物服务记录', 'verbose_name_plural': '宠物服务记录'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_content',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_duration',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_end_time',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_result',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_start_time',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_title',
        ),
        migrations.RemoveField(
            model_name='petservicerecord',
            name='service_type',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='petcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='petcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='petdiary',
            name='author',
            field=models.ForeignKey(blank=True, help_text='可以是宠物主人或服务提供者', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_diaries', to='user.user', verbose_name='记录人'),
        ),
        migrations.AddField(
            model_name='petdiary',
            name='diary_type',
            field=models.CharField(choices=[('daily', '日常记录'), ('service', '服务记录')], default='daily', max_length=10, verbose_name='日记类型'),
        ),
        migrations.AddField(
            model_name='petservicerecord',
            name='actual_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际时长(分钟)'),
        ),
        migrations.AddField(
            model_name='petservicerecord',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间'),
        ),
        migrations.AddField(
            model_name='petservicerecord',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间'),
        ),
        migrations.AddField(
            model_name='petservicerecord',
            name='rating',
            field=models.IntegerField(blank=True, help_text='1-5分', null=True, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='petservicerecord',
            name='related_diary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_record', to='pet.petdiary', verbose_name='关联服务日记'),
        ),
        migrations.AddField(
            model_name='petservicerecord',
            name='service_summary',
            field=models.TextField(blank=True, null=True, verbose_name='服务总结'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='品种'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pet.petcategory', verbose_name='宠物分类'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='毛色'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', '雄性'), ('F', '雌性'), ('U', '未知')], default='U', max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health_status',
            field=models.TextField(blank=True, null=True, verbose_name='健康状况'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宠物名称'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='user.user', verbose_name='主人'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personality',
            field=models.TextField(blank=True, null=True, verbose_name='性格特点'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccination_record',
            field=models.TextField(blank=True, null=True, verbose_name='疫苗记录'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='单位：千克', max_digits=5, null=True, verbose_name='体重(kg)'),
        ),
        migrations.AlterField(
            model_name='petcategory',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='分类图标'),
        ),
        migrations.AlterField(
            model_name='petcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='petcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='petcategory',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='petdiary',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='petdiary',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='petservicerecord',
            name='pet_condition_after',
            field=models.TextField(blank=True, null=True, verbose_name='服务后宠物状况'),
        ),
        migrations.AlterField(
            model_name='petservicerecord',
            name='pet_condition_before',
            field=models.TextField(blank=True, null=True, verbose_name='服务前宠物状况'),
        ),
        migrations.AlterField(
            model_name='petservicerecord',
            name='related_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_record', to='bill.serviceorder', verbose_name='关联订单'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', '-created_at'], name='pet_owner_i_16697f_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['category', 'is_deleted'], name='pet_categor_62d5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='petdiary',
            index=models.Index(fields=['pet', '-diary_date'], name='pet_diary_pet_id_74eb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='petdiary',
            index=models.Index(fields=['author', '-created_at'], name='pet_diary_author__baf39a_idx'),
        ),
        migrations.AddIndex(
            model_name='petdiary',
            index=models.Index(fields=['diary_type', '-created_at'], name='pet_diary_diary_t_f8baba_idx'),
        ),
        migrations.AddIndex(
            model_name='petservicerecord',
            index=models.Index(fields=['related_order'], name='pet_service_related_69fb87_idx'),
        ),
        migrations.AddIndex(
            model_name='petservicerecord',
            index=models.Index(fields=['-actual_start_time'], name='pet_service_actual__06ac15_idx'),
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
        migrations.AlterModelTable(
            name='petcategory',
            table='pet_category',
        ),
        migrations.AlterModelTable(
            name='petdiary',
            table='pet_diary',
        ),
        migrations.AlterModelTable(
            name='petservicerecord',
            table='pet_service_record',
        ),
    ]
