# Generated by Django 5.2.5 on 2025-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_pet_options_alter_petcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdiary',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='封面图片'),
        ),
    ]
