# Generated by Django 5.2.5 on 2025-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='icon',
            field=models.URLField(blank=True, verbose_name='图标地址'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='icon',
            field=models.URLField(blank=True, verbose_name='图标地址'),
        ),
    ]
