# Generated by Django 5.2.5 on 2025-11-04 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_additionalservice_icon_servicemodel_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalservice',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '附加服务', 'verbose_name_plural': '附加服务'},
        ),
        migrations.AlterModelOptions(
            name='pettype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': '宠物类型', 'verbose_name_plural': '宠物类型'},
        ),
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': '基础服务', 'verbose_name_plural': '基础服务'},
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='pettype',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='applicable_pets',
            field=models.ManyToManyField(blank=True, help_text='该服务适用的宠物类型，留空表示适用所有类型', related_name='services', to='service.pettype', verbose_name='适用宠物类型'),
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='applicable_pets',
            field=models.ManyToManyField(blank=True, help_text='该附加服务适用的宠物类型，留空表示适用所有类型', related_name='additional_services', to='service.pettype', verbose_name='适用宠物类型'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='icon',
            field=models.URLField(blank=True, help_text='服务图标URL', verbose_name='图标地址'),
        ),
        migrations.AlterField(
            model_name='additionalservice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='该类型宠物的基础上门服务费', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础上门价格'),
        ),
        migrations.AlterField(
            model_name='pettype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='该服务的基础价格', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础价格'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='icon',
            field=models.URLField(blank=True, help_text='服务图标URL', verbose_name='图标地址'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AddIndex(
            model_name='additionalservice',
            index=models.Index(fields=['is_active', 'sort_order'], name='service_add_is_acti_c4c890_idx'),
        ),
        migrations.AddIndex(
            model_name='pettype',
            index=models.Index(fields=['is_active', 'sort_order'], name='service_pet_is_acti_bccbdd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemodel',
            index=models.Index(fields=['is_active', 'sort_order'], name='service_ser_is_acti_d506c6_idx'),
        ),
    ]
