# Generated by Django 5.2.5 on 2025-08-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='分类名称')),
                ('url', models.URLField(verbose_name='图片链接')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('link', models.URLField(verbose_name='跳转链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banners',
                'ordering': ['sort_order'],
            },
        ),
    ]
