# Generated by Django 5.2.5 on 2025-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='跳转链接'),
        ),
    ]
