# Generated by Django 5.2.5 on 2025-08-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_banner_updated_at_alter_banner_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, help_text='点击轮播图后跳转的链接，可以是内部路由或外部链接', null=True, verbose_name='跳转链接'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='数字越小越靠前显示', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('home', '首页轮播'), ('community', '社区轮播'), ('service', '服务轮播')], default='home', help_text='用于区分不同页面的轮播图', max_length=20, verbose_name='轮播图类型'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(help_text='轮播图图片地址', verbose_name='图片链接'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['type', 'is_active'], name='banner_type_553fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['sort_order'], name='banner_sort_or_c64ff1_idx'),
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
    ]
