# Generated by Django 5.2.5 on 2025-11-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrayAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('dog', '狗'), ('cat', '猫'), ('rabbit', '兔子'), ('bird', '鸟'), ('other', '其他')], db_index=True, max_length=20, verbose_name='动物类型')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('breed', models.CharField(blank=True, max_length=50, null=True, verbose_name='品种')),
                ('primary_color', models.CharField(max_length=30, verbose_name='主要颜色')),
                ('secondary_color', models.CharField(blank=True, max_length=30, null=True, verbose_name='次要颜色')),
                ('size', models.CharField(choices=[('tiny', '迷你型'), ('small', '小型'), ('medium', '中型'), ('large', '大型')], max_length=20, verbose_name='体型大小')),
                ('gender', models.CharField(choices=[('male', '雄性'), ('female', '雌性'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='性别')),
                ('estimated_age', models.CharField(blank=True, help_text='例如：幼崽、1-2岁、老年等', max_length=30, null=True, verbose_name='估计年龄')),
                ('distinctive_features', models.TextField(blank=True, help_text='例如：左耳有缺口、尾巴断了一截、额头有白斑等', null=True, verbose_name='显著特征')),
                ('health_status', models.CharField(choices=[('good', '良好'), ('normal', '一般'), ('injured', '受伤'), ('sick', '生病'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='健康状态')),
                ('is_friendly', models.BooleanField(default=True, verbose_name='是否亲人')),
                ('behavior_notes', models.TextField(blank=True, help_text='例如：胆小、活泼、喜欢晒太阳等', null=True, verbose_name='行为特点')),
                ('province', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='城市')),
                ('district', models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='区县')),
                ('detail_address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('location_tips', models.CharField(blank=True, help_text='例如：常在垃圾桶附近、喜欢在树下休息等', max_length=200, null=True, verbose_name='位置提示')),
                ('main_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='主图片URL')),
                ('image_urls', models.JSONField(blank=True, default=list, help_text='JSON格式的图片URL列表', verbose_name='其他图片URLs')),
                ('status', models.CharField(choices=[('active', '活跃'), ('missing', '失踪'), ('rescued', '已救助'), ('adopted', '已领养')], db_index=True, default='active', max_length=20, verbose_name='当前状态')),
                ('first_seen_date', models.DateField(help_text='第一次看到这只动物的日期', verbose_name='首次发现日期')),
                ('last_seen_date', models.DateField(help_text='最近一次看到这只动物的日期', verbose_name='最后见到日期')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='包括评论、点赞等', verbose_name='互动次数')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='补充说明')),
                ('is_active', models.BooleanField(default=True, help_text='是否显示在列表中', verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_animals', to='user.user', verbose_name='记录者')),
            ],
            options={
                'verbose_name': '流浪动物',
                'verbose_name_plural': '流浪动物',
                'db_table': 'stray_animals',
                'ordering': ['-last_seen_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrayAnimalInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('comment', '评论'), ('like', '点赞'), ('feed', '投喂'), ('sighting', '目击'), ('care', '照料')], max_length=20, verbose_name='互动类型')),
                ('content', models.TextField(blank=True, help_text='评论内容或其他描述', null=True, verbose_name='互动内容')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='互动位置纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='互动位置经度')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='图片URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='互动时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='strays.strayanimal', verbose_name='流浪动物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_interactions', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '动物互动',
                'verbose_name_plural': '动物互动',
                'db_table': 'stray_animal_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='strayanimal',
            index=models.Index(fields=['status', '-last_seen_date'], name='stray_anima_status_74ab71_idx'),
        ),
        migrations.AddIndex(
            model_name='strayanimal',
            index=models.Index(fields=['province', 'city', 'district'], name='stray_anima_provinc_293880_idx'),
        ),
        migrations.AddIndex(
            model_name='strayanimal',
            index=models.Index(fields=['animal_type', 'status'], name='stray_anima_animal__79e865_idx'),
        ),
        migrations.AddIndex(
            model_name='strayanimal',
            index=models.Index(fields=['latitude', 'longitude'], name='stray_anima_latitud_0f59ac_idx'),
        ),
        migrations.AddIndex(
            model_name='strayanimalinteraction',
            index=models.Index(fields=['animal', 'interaction_type'], name='stray_anima_animal__2f4571_idx'),
        ),
        migrations.AddIndex(
            model_name='strayanimalinteraction',
            index=models.Index(fields=['user', 'created_at'], name='stray_anima_user_id_dbd611_idx'),
        ),
    ]
