# Generated by Django 5.2.5 on 2025-11-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strays', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strayanimal',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏次数'),
        ),
        migrations.CreateModel(
            name='StrayAnimalFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='strays.strayanimal', verbose_name='流浪动物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_favorites', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '动物收藏',
                'verbose_name_plural': '动物收藏',
                'db_table': 'stray_animal_favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='stray_anima_user_id_20baa5_idx'), models.Index(fields=['animal', '-created_at'], name='stray_anima_animal__b406ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'animal'), name='unique_user_animal_favorite')],
            },
        ),
        migrations.CreateModel(
            name='StrayAnimalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('fake_info', '虚假信息'), ('inappropriate', '不当内容'), ('spam', '垃圾信息'), ('abuse', '恶意攻击'), ('duplicate', '重复发布'), ('other', '其他')], max_length=20, verbose_name='举报类型')),
                ('reason', models.TextField(verbose_name='举报原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已处理'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=20, verbose_name='处理状态')),
                ('handler_note', models.TextField(blank=True, null=True, verbose_name='处理说明')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='strays.strayanimal', verbose_name='被举报的动物')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to='user.user', verbose_name='处理人')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='strays.strayanimalinteraction', verbose_name='被举报的互动')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='user.user', verbose_name='举报人')),
            ],
            options={
                'verbose_name': '举报记录',
                'verbose_name_plural': '举报记录',
                'db_table': 'stray_animal_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='stray_anima_status_72f0e3_idx'), models.Index(fields=['reporter', '-created_at'], name='stray_anima_reporte_028ca9_idx'), models.Index(fields=['animal', '-created_at'], name='stray_anima_animal__2ccf39_idx')],
            },
        ),
    ]
