# Generated by Django 5.2.5 on 2025-08-26 05:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='手机号格式不正确', regex='^\\+?1?\\d{9,15}$')], verbose_name='手机号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '超级管理员',
                'verbose_name_plural': '超级管理员',
                'db_table': 'super_admins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='用户名')),
                ('avatar', models.URLField(blank=True, default='', max_length=500, verbose_name='头像')),
                ('bio', models.CharField(blank=True, default='', max_length=200, verbose_name='个人简介')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='手机号格式不正确', regex='^\\+?1?\\d{9,15}$')], verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他'), ('U', '未设置')], default='U', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('openid', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信小程序用户唯一标识符')),
                ('unionid', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信标识符')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP用户')),
                ('vip_level', models.IntegerField(default=0, verbose_name='VIP等级')),
                ('vip_expired_at', models.DateTimeField(blank=True, null=True, verbose_name='VIP到期时间')),
                ('followers_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='粉丝数')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='关注数')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='帖子数')),
                ('likes_received', models.PositiveIntegerField(default=0, verbose_name='获赞数')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='是否认证')),
                ('verification_type', models.CharField(blank=True, default='', max_length=50, verbose_name='认证类型')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='认证时间')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='用户等级')),
                ('exp', models.PositiveIntegerField(default=0, verbose_name='经验值')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
                ('gold', models.IntegerField(default=0, verbose_name='金币')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开资料')),
                ('allow_message', models.BooleanField(default=True, verbose_name='允许私信')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'indexes': [models.Index(fields=['phone'], name='users_phone_af6883_idx'), models.Index(fields=['is_verified', '-followers_count'], name='users_is_veri_984d51_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx'), models.Index(fields=['last_active_at'], name='users_last_ac_ace5f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=30, verbose_name='收货人姓名')),
                ('receiver_phone', models.CharField(max_length=17, verbose_name='收货人电话')),
                ('province', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('detail_address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='纬度')),
                ('access_instructions', models.TextField(blank=True, null=True, verbose_name='入户说明')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='地址标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='user.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'user_addresses',
            },
        ),
    ]
